<?xml version="1.0" encoding="utf-8"?><Database Name="LinQToSQL" Class="CSDLTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ADMIN\TIENDUNGVUPHAM;Initial Catalog=LinQToSQL;Integrated Security=True" SettingsObjectName="UpdateData13.Properties.Settings" SettingsPropertyName="LinQToSQLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="MaDanhMuc" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDanhMuc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="DanhMuc_SanPham" Member="SanPhams" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSP" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaDanhMuc" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="DanhMuc_SanPham" Member="DanhMuc" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="DanhMuc" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteProduct" Method="DeleteProduct">
    <Parameter Name="maSP" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateCostProduct" Method="UpdateCostProduct">
    <Parameter Name="maSP" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="donGia" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DetailProduct" Method="DetailProduct">
    <Parameter Name="maSP" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="DetailProductResult">
      <Column Name="MaSP" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaDanhMuc" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TenDanhMuc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertProduct" Method="InsertProduct">
    <Parameter Name="maSP" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="tenSP" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="donGia" Type="System.Double" DbType="Float" />
    <Parameter Name="maDanhMuc" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TakeAllProduct" Method="TakeAllProduct">
    <ElementType Name="TakeAllProductResult">
      <Column Name="MaSP" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaDanhMuc" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>